# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./SimpleLabel.h \
		./Constants.h \
		./Monitor.h \
		./About.h \
		./SaveDialog.h

SOURCES += ./main.cpp \
		./SimpleLabel.cpp \
		./Monitor.cpp \
		./About.cpp \
		./SaveDialog.cpp

FORMS += ./SimpleLabel.ui \
		./AboutDlg.ui \
		./SaveDialog.ui

RESOURCES += ./SimpleLabel.qrc
